### ISSUE TITLE
crear github page

### ISSUE THREAD

**Issue by urkonn** [PythonMexico/pythonmexico-site-2014#3]
- [ ] crear branch gh-pages
- [ ] apuntar DNS del dominio a github
  https://help.github.com/articles/setting-up-a-custom-domain-with-pages

**Comment by Carlangueitor** [comment]
Recomiendo que el output de pelican no esté en el branch `master`, y que lo jalemos a `gh-pages` por medio de [ghp-import](https://github.com/davisp/ghp-import).

**Comment by urkonn** [comment]
agree :+1:

**Comment by erikriver** [comment]
Hola, ¿a donde apunto el dominio? 
van a usar github pages? 
creo el CNAME a pythonmexico.github.io?
alguien lo va a hospedar? pasen la IP
van a querer que lo hospede? me avisan.

**Comment by urkonn** [comment]
Hola @erikriver 

Se va a usar github pages.
Si en un futuro usamos otra cosa para hacer el sitio más dinámico podríamos hospedar en otro lado, pero por ahora github es suficiente.

**Comment by erikriver** [comment]
@urkonn enterado

entonces creo de una vez el CNAME a pythonmexico.github.io?

**Comment by urkonn** [comment]
@erikriver no urge pero si puedes ir creándolo estaría bien.

Sería una página de proyecto https://help.github.com/articles/user-organization-and-project-pages#project-pages

Gracias.

**Comment by ghost** [comment]
Hola...

¿Cual es el estatus actual del proyecto?

**Comment by urkonn** [comment]
hola @mauriciobaeza 

El proyecto ya lleva rato parado, ¿te interesa colaborar?

**Comment by ghost** [comment]
claro, a mi y a todos los compañeros en Python Cabal: https://github.com/LinuxCabal

Ustedes tienen el dominio: http://python.org.mx ?

Aquí hay uno listo para usarse: https://github.com/PyAr/pyarweb

Un abrazo

**Comment by urkonn** [comment]
Excelente! bienvenidos!

El tema de los dominios es algo que creo que hay que tratar en la lista de correo.

Se había decidido hace tiempo tener un sitio aquí en github para que varias personas pudiesen colaborar con su construcción y no depender de una sola persona que se encargue de hostearla, administrarla y además evitar malos entendidos.

Por supuesto que algo con django estaría mucho mejor, pero no sé qué tan viable sea en este momento. Habrá que consultarlo con la comunidad.

**Comment by urkonn** [comment]
@erikriver tu puedes modificar los registros del dominio?

**Comment by ghost** [comment]
Yo le escribi al dueño de python.org.mx y me dijo que sin problemas le pasamos los DNS que queramos, es decir, hay total disponibilidad.

**Comment by urkonn** [comment]
OK pues entonces a darle :+1:

**Comment by urkonn** [comment]
Acabo de crear un canal en Gitter, inviten a más gente.

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/PythonMexico/pythonmexico-site-2014?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by ghost** [comment]
Lo voy a publicar en las listas de correo...

**Comment by ghost** [comment]
Los temas relacionados... ¿los vemos aquí en Github o en la lista de correo?...

Como vamos a usar un hosting con más ventajas que github, creo que se podría cerrar este tema... ¿que opinan?

**Comment by erikriver** [comment]
Hola, desde hace años estuve a cargo de python.org.mx, por falta de tiempo dejé de hacerlo, Jorge Gajon (dueño del dominio) tiene registrado mis DNS y sin problema puedo apoyarlos redireccionarlos a donde lo soliciten o les puedo dar hosting con Python o ustedes solicitar a Jorge el cambio de DNS, incluso también hay disponibilidad del dueño de pythonmexico.com/org para apuntar al nuevo sitio.

En este momento me encuentro en el PyCon, cualquier duda o apoyo cuenten conmigo

**Comment by urkonn** [comment]
gracias @erikriver 

@mauriciobaeza lo vemos en la lista de correo para que todos estén enterados, lo del desarrollo lo podemos ver aquí y en gitter.im

**Comment by ghost** [comment]
Gracias @erikriver... si, Jorge ya me confirmo que puede cambiar los DNS cuando le indiquemos...
¿que caracteristicas tiene el hosting que puedes ofrecer?
Excelente, pidele al dueño de esos dominios que redireccionen a python.org.mx

Saludos

**Comment by erikriver** [comment]
@mauriciobaeza el hosting puede ser en DigitalOcean o AWS, en DO les puedo asignar una instancia de 1GB de ram exclusiva para el sitio, o en AWS estarían en una instancia compartida m1.small con ubuntu 12.04, ahí solo tengo un sitio Plone

**Comment by Carlangueitor** [comment]
DO +1

**Comment by urkonn** [comment]
¿quién se encargaría del sitio?, lo ideal es que sea entre varios para que no caiga en descuido.
¿cómo ven?

**Comment by ghost** [comment]
¿Por que dejarlo a unos cuantos de nosotros cuando puede ser cualquiera de la comunidad?, lo que quiero decir es que si construimos correctamente la infraestructura aquí en Github, la comunidad puede muy bien hacerse cargo como lo hace la comunidad argentina... como lo mencionas, creo que esto es mejor discutirlo en la lista de correo...

**Comment by Jzarecta** [comment]
yo soy mas de la idea de delegarlo a python.org esa comunidad ya esta
organizada, ya tiene una fundacion y tienen todo lo necesario para ayudar.

2015-04-09 17:22 GMT-05:00 Mauricio Baeza notifications@github.com:

> ¿Por que dejarlo a unos cuantos de nosotros cuando puede ser cualquiera de
> la comunidad?, lo que quiero decir es que si construimos correctamente la
> infraestructura aquí en Github, la comunidad puede muy bien hacerse cargo
> como lo hace la comunidad argentina... como lo mencionas, creo que esto es
> mejor discutirlo en la lista de correo...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PythonMexico/pythonmexico-site-2014/issues/3#issuecomment-91370896
> .

## 

Alexandro Colorado
Apache OpenOffice Contributor
882C 4389 3C27 E8DF 41B9  5C4C 1DB7 9D1C 7F4C 2614

**Comment by ghost** [comment]
Delegar que?, la creación del sitio web de Python México que es lo que estamos discutiendo aquí?

**Comment by urkonn** [comment]
@mauriciobaeza me refería a la operación, no al desarrollo o creación de contenido.

Deberíamos de ver cómo le hacen otras comunidades y organizarnos un poco mejor :)

**Comment by Jzarecta** [comment]
si muchos del look and feel ya esta dentro del web team. El contenido si,
puede variar y se podria manejar en un mini-wiki.

2015-04-09 17:36 GMT-05:00 Julio Acuña notifications@github.com:

> @mauriciobaeza https://github.com/mauriciobaeza me refería a la
> operación, no al desarrollo o creación de contenido.
> 
> Deberíamos de ver cómo le hacen otras comunidades y organizarnos un poco
> mejor :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PythonMexico/pythonmexico-site-2014/issues/3#issuecomment-91372711
> .

## 

Alexandro Colorado
Apache OpenOffice Contributor
882C 4389 3C27 E8DF 41B9  5C4C 1DB7 9D1C 7F4C 2614

**Comment by ghost** [comment]
@urkonn  y yo me refiero a todos esos rubros, la comunidad argentina, creo, es la línea a seguir: abiertos, colaborativos, comprometidos, y ya tienen un nuevo sitio listo para que solo lo usemos: https://github.com/PyAr/pyarweb

**Comment by Jzarecta** [comment]
Creo que es una decision importante que se debe de tomar la direccion.
Hacer nuestro propio sitio y mantenerlo vs reutilizar el de python.org y
ser parte del agregado. Donde esto se mantendra centralizadamente y todos
seremos usuarios 100% de sitio.

Lo que quiero evitar es poner un sitio muy padre que termine abandonado en
5 anios mas por falta de tiempo, dinero, ganas, direccion de github, etc
etc.

2015-04-09 17:48 GMT-05:00 Mauricio Baeza notifications@github.com:

> @urkonn https://github.com/urkonn y yo me refiero a todos esos rubros,
> la comunidad argentina, creo, es la línea a seguir: abiertos,
> colaborativos, comprometidos, y ya tienen un nuevo sitio listo para que
> solo lo usemos: https://github.com/PyAr/pyarweb
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PythonMexico/pythonmexico-site-2014/issues/3#issuecomment-91374165
> .

## 

Alexandro Colorado
Apache OpenOffice Contributor
882C 4389 3C27 E8DF 41B9  5C4C 1DB7 9D1C 7F4C 2614

**Comment by urkonn** [comment]
@mauriciobaeza yo no le doy acceso a mis servidores a cualquiera jajaja
ya en serio, por supuesto que ese es el ideal pero creo que hay que encontrar las formas ya que hasta ahora la comunidad no ha sido muy activa, hay que promover la participación.

ya había visto ese repo y su sitio está bastante bien, como dices es únicamente cuestión de usarlo.

**Comment by ghost** [comment]
@urkonn , jajajaj... por mi parte si es alguien de la comunidad, si, jejeje

claro, estoy de acuerdo contigo, no ha sido muy activa pero eso puede cambiar, solo, hay que ponerse a trabajar...

si, me gusta mucho como quedo el sitio de los compañeros argentinos...

Estoy escribiendo un correo en las listas, ahí le damos seguimieno... ¿les parece?

Como decía en un comentario anterior, el tema inicial de este issue esta sobrepasado, creo que debería cerrarse... ya abrir otros de ser necesarios...

Slaudos

**Comment by urkonn** [comment]
@mauriciobaeza me parece bien, seguimos en la lista de correo y cerramos el issue

¿podrías entrar a gitter.im?
